/**
 * Generate docs/manual/cli.md from the CLI catalogue (ADR 0159, 0165).
 * Run with `mise run docs:cli`; `--check` exits 1 when the file is stale.
 */
import { CLI_COMMANDS, DATA_DIR_LAYOUT, EXIT, MIN_BUN_VERSION, type CliTransport } from '../../src/lib/schemas/cli';

const OUT = new URL('../../docs/manual/cli.md', import.meta.url).pathname;

const TRANSPORT: Record<CliTransport, string> = {
	socket: 'needs the running server (admin socket)',
	'socket-or-direct': 'uses the running server when there is one, else writes the database directly',
	offline: 'refuses while the server runs',
	none: 'talks to neither the server nor the database'
};

const lines: string[] = [
	'# CLI reference',
	'',
	'<!-- Generated by `mise run docs:cli` from src/lib/schemas/cli.ts — do not edit by hand. -->',
	'',
	`\`granary\` needs Bun ${MIN_BUN_VERSION} or newer. Every command takes \`--data <dir>\`; without it the data`,
	'directory is `GRANARY_DATA_DIR`, else `$XDG_STATE_HOME/granary`, else `~/.local/state/granary`.',
	'The systemd unit uses `/var/lib/granary`.',
	'',
	'Commands that change something talk to the running server over its admin socket',
	`(\`<data>/${DATA_DIR_LAYOUT.adminSocket}\`, mode 0600), so the server sees the change at once. When no server is`,
	'running, most of them write the database directly instead.',
	'',
	'## Exit codes',
	'',
	'| Code | Meaning |',
	'|---|---|',
	`| ${EXIT.ok} | success |`,
	`| ${EXIT.error} | the command failed (the message says why) |`,
	`| ${EXIT.usage} | unknown command or option, missing argument |`,
	`| ${EXIT.serverNotRunning} | the command needs the running server and there is none |`,
	'',
	'## Commands',
	''
];

for (const c of CLI_COMMANDS) {
	const usage = ['granary', c.name, ...c.args.map((a) => `<${a}>`)].join(' ');
	lines.push(`### \`${usage}\``, '', c.name === 'serve' ? `${c.description}.` : `${c.description}. It ${TRANSPORT[c.transport]}.`, '');
	if (c.options.length) {
		lines.push('| Option | Description |', '|---|---|');
		for (const o of c.options) {
			const flag = o.type === 'string' ? `--${o.name} <value>` : `--${o.name}`;
			lines.push(`| \`${flag}\` | ${o.description}${o.default ? ` (default \`${o.default}\`)` : ''} |`);
		}
		lines.push('');
	}
}

const text = lines.join('\n');
if (process.argv.includes('--check')) {
	const current = await Bun.file(OUT).text().catch(() => '');
	if (current !== text) {
		console.error('docs/manual/cli.md is stale; run `mise run docs:cli`');
		process.exit(1);
	}
	console.log('docs/manual/cli.md is up to date');
} else {
	await Bun.write(OUT, text);
	console.log(`wrote ${OUT}`);
}
