/**
 * `credentials/main` — issued credentials (ADR 0133): S3 access keys scoped
 * to buckets (`object-rw`, `object-ro`, `admin`), exe.dev VM tokens and
 * OTLP bearer tokens. Secret material is generated by the server and passed
 * in, so the chart stays deterministic. Revoked credentials stay listed.
 */
import { statechart } from '@tinyactors/node';
import type { IssueCredentialRequest } from '../schemas';
import { answer } from '../io/reply';

export const CREDENTIALS_ADDRESS = { family: 'credentials', name: 'main' } as const;

export type CredentialKind = 's3' | 'exe-vm-token' | 'otlp-bearer';
export type CredentialScope = 'object-rw' | 'object-ro' | 'admin';

export interface Credential {
	id: string;
	kind: CredentialKind;
	scope: CredentialScope | null;
	buckets: string[];
	accessKeyId: string | null;
	secretAccessKey: string | null;
	token: string | null;
	label: string | null;
	revoked: boolean;
}

export interface CredentialsData {
	creds: Credential[];
	out: unknown;
}

export const CREDENTIAL_EVENTS = {
	issue: 'credential.issue',
	revoke: 'credential.revoke',
	byKey: 'credential.by-key',
	byToken: 'credential.by-token',
	anyActive: 'credential.any-active'
} as const;

export interface IssueEvent {
	id: string;
	request: IssueCredentialRequest;
	/** Generated by the server: access key id + secret, or a token. */
	material: { accessKeyId: string; secretAccessKey: string; token: string };
}

export const credentialsChart = statechart<CredentialsData>({ family: 'credentials', revision: 'v1' })
	.dataExpression('creds', () => [])
	.data('out', null)
	.state('ready', (s) =>
		s
			.on(
				CREDENTIAL_EVENTS.issue,
				answer<CredentialsData, IssueEvent>((d, e) => {
					const r = e.request;
					const c: Credential =
						r.kind === 's3'
							? {
									id: e.id,
									kind: 's3',
									scope: r.scope,
									buckets: [...r.buckets],
									accessKeyId: e.material.accessKeyId,
									secretAccessKey: e.material.secretAccessKey,
									token: null,
									label: null,
									revoked: false
								}
							: {
									id: e.id,
									kind: r.kind,
									scope: null,
									buckets: [],
									accessKeyId: null,
									secretAccessKey: null,
									token: e.material.token,
									label: r.label,
									revoked: false
								};
					d.creds.push(c);
					return { ...c };
				})
			)
			.on(
				CREDENTIAL_EVENTS.revoke,
				answer<CredentialsData, { id: string }>((d, e) => {
					const c = d.creds.find((x) => x.id === e.id);
					if (!c) return { error: `No credential ${e.id}`, status: 404 };
					c.revoked = true;
					return { ok: true };
				})
			)
			.on(
				CREDENTIAL_EVENTS.byKey,
				answer<CredentialsData, { accessKeyId: string }>((d, e) => {
					const c = d.creds.find((x) => x.kind === 's3' && x.accessKeyId === e.accessKeyId);
					return c ? { ...c } : null;
				})
			)
			.on(
				CREDENTIAL_EVENTS.byToken,
				answer<CredentialsData, { token: string; kind: CredentialKind }>((d, e) => {
					const c = d.creds.find((x) => x.kind === e.kind && x.token === e.token);
					return c ? { ...c } : null;
				})
			)
			.on(
				CREDENTIAL_EVENTS.anyActive,
				answer<CredentialsData, { kind: CredentialKind }>((d, e) => d.creds.some((x) => x.kind === e.kind && !x.revoked))
			)
	);
